version: '3.4'

services:
  api-server:
    image: job-warehouse-be
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # volumes:
    #   ./:./src

  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=Web_monquachothay
    expose:
      - 3306
    ports:
      - "3306:3306"

